package GUI;
//librerias a usar

import TXT.*;//importado para usar todas las clases del package TXT
import Class.*;//importardo para usar todas las clases del package Class
import java.util.List;//importado para usar ArrayList
import javax.swing.JOptionPane;//importado para usar JopcionPane

public class VentanaCvPersonalizado extends javax.swing.JFrame {

    public VentanaCvPersonalizado() {
        initComponents();
        this.setLocationRelativeTo(null);//acomodar la pantalla en el centro

        //cargar informacion apenas se ejecute la app
        cargarDatosCombox1();
        cargarDatosCombox2();
        cargarDatoscombox3();
    }
//metodo para cargar los datos en el combobox1

    private void cargarDatosCombox1() {
        //atributos
        DatosPersonales datosPersonales = new DatosPersonales();
        DatosPersonalesTXT datostxt = new DatosPersonalesTXT(datosPersonales);
        datostxt.leerDatos();//llamado de la funcion
        //recorrer un list sacado de:
        //https://www.arquitecturajava.com/java-foreach-y-sus-opciones/
        List<String> listaDatos = datostxt.leerDatos();//crear un lista y asignarle lo de la clase datostxt.leerDatos
        
        for (String datos : listaDatos) {//for each para recorrer la lista
            jComboBox1.addItem(datos);//agregar datos en el combobox
        }
    }

//metodo para cargar los datos en el combobox 2
    private void cargarDatosCombox2() {
        //atributos
        ExperienciaLaboral experiencia = new ExperienciaLaboral();
        ExperienciaLaboralTXT experienciatxt = new ExperienciaLaboralTXT(experiencia);

        experienciatxt.leerDatos();//llamado de la funcion
        //recorrer un list sacado de:
        //https://www.arquitecturajava.com/java-foreach-y-sus-opciones/
        List<String> listaDatos = experienciatxt.leerDatos();//crear un lista y asignarle lo de la clase Experiencialaboraltxt.leerDatos
        for (String datos : listaDatos) {//for each para recorrer la lista
            jComboBox2.addItem(datos);//agregar datos en el combobox
        }
    }
//metodo para cargar los datos en el combobox 3
    private void cargarDatoscombox3() {
        //atributos
        InformacionContacto informacion = new InformacionContacto();
        InformacionContactoTXT informaciontxt = new InformacionContactoTXT(informacion);
        informaciontxt.leerDatos();//llamado de la funcion
        //recorrer un list sacado de:
        //https://www.arquitecturajava.com/java-foreach-y-sus-opciones/
        List<String> listaDatos = informaciontxt.leerDatos();//crear un lista y asignarle lo de la clase Informaciontxt.leerDatos
        for (String datos : listaDatos) {//for each para recorrer la lista
            jComboBox3.addItem(datos);//agregar datos en el combobox
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        botonAtras = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccionar datos para CV");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        botonAtras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Selecciona Datos Personales");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Seleccionar Informacion para Cv");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Selecciona Experiencia Laboral");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Selecciona Informacion De Contacto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(botonAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(botonGuardar)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(botonSalir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAtras)
                    .addComponent(botonSalir)
                    .addComponent(botonGuardar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//boton para guardar informacion
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        CvPersonalizado cv = new CvPersonalizado();//atributo
//guardar lo seleccionado en el combobox
        String DatosPersonales = (String) jComboBox1.getSelectedItem();
        String ExperienciaLaboral = (String) jComboBox2.getSelectedItem();
        String InformacionContacto = (String) jComboBox3.getSelectedItem();

        cv.crearArchivo();//llamar al metodo para crear txt
        cv.agregarDatos(DatosPersonales, ExperienciaLaboral, InformacionContacto);//pasar los atributos a 
        JOptionPane.showMessageDialog(null, "Curriculom creado exitosamente");//mensaje de exitoso


    }//GEN-LAST:event_botonGuardarActionPerformed
//boton para salir de la app
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        //opcion de salir sacado de Ejemplos ficheros dado por la tutora Adriana Rubio Escobar 
        //https://aprende.uned.ac.cr/mod/forum/discuss.php?d=113727#:~:text=de%20gran%20utilidad.-,Sistema,-.rar
        int opcion = JOptionPane.showConfirmDialog(null, "Está seguro de salir?", "Alerta!",
                JOptionPane.YES_NO_OPTION);
        if (opcion == 0)
            System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed
//boton de atras,muestra la ventana de opciones
//sacado de :https://www.youtube.com/watch?v=L3r2Yn8VkFU&list=PLipD9tBhN-KuqR59uP5XoLvfBNHHeKToz&index=4&ab_channel=DAVID
    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        VentanaOpciones abrir = new VentanaOpciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCvPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCvPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCvPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCvPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCvPersonalizado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
