package GUI;

import TXT.DatosPersonalesTXT;
import Class.*;
import java.util.Calendar;
import javax.swing.JOptionPane;

public class VentanaDatosPersonales extends javax.swing.JFrame {

    public VentanaDatosPersonales() {
        initComponents();
        this.setLocationRelativeTo(null);//acomodar la pantalla en el centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatosPersonales = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        Cedula = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        FechaNacimiento = new javax.swing.JLabel();
        Objetivo = new javax.swing.JLabel();
        textoID = new javax.swing.JFormattedTextField();
        textoCedula = new javax.swing.JFormattedTextField();
        textoNombre = new javax.swing.JFormattedTextField();
        textoDireccion = new javax.swing.JFormattedTextField();
        textoCorreo = new javax.swing.JFormattedTextField();
        textoObjetivo = new javax.swing.JFormattedTextField();
        BotonGuardar = new javax.swing.JButton();
        BotonSiguiente = new javax.swing.JButton();
        BotonAtras = new javax.swing.JButton();
        Nacionalidad = new javax.swing.JLabel();
        textoNacionalidad = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        textoEstado = new javax.swing.JFormattedTextField();
        textoFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos personales");

        DatosPersonales.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        DatosPersonales.setText("Datos Personales");

        ID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ID.setText("ID");

        Cedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cedula.setText("Cedula");

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nombre.setText("Nombre");

        Direccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Direccion.setText("Direccion");

        Correo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Correo.setText("Correo");

        FechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FechaNacimiento.setText("Fecha Nacimiento");

        Objetivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Objetivo.setText("Objetivo");

        textoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoIDKeyTyped(evt);
            }
        });

        textoCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoCedulaKeyTyped(evt);
            }
        });

        BotonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonSiguiente.setText("Siguiente");
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });

        BotonAtras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonAtras.setText("Atras");
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });

        Nacionalidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nacionalidad.setText("Nacionalidad");

        textoNacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNacionalidadKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Estado Civil");

        textoEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoEstadoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Cedula, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(ID)
                            .addGap(21, 21, 21)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre)
                            .addComponent(Correo)
                            .addComponent(Direccion)
                            .addComponent(FechaNacimiento)
                            .addComponent(Objetivo)
                            .addComponent(Nacionalidad)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonAtras)
                                .addGap(109, 109, 109)
                                .addComponent(BotonGuardar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textoCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(textoDireccion)
                        .addComponent(textoNombre)
                        .addComponent(textoID)
                        .addComponent(textoCedula, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(textoObjetivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNacionalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DatosPersonales)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonSiguiente)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DatosPersonales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(textoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula)
                    .addComponent(textoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion)
                    .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(textoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FechaNacimiento)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nacionalidad)
                            .addComponent(textoNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Objetivo)
                            .addComponent(textoObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonGuardar)
                            .addComponent(BotonSiguiente)
                            .addComponent(BotonAtras))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//boton de atras,muestra la ventana de opciones
//sacado de :https://www.youtube.com/watch?v=L3r2Yn8VkFU&list=PLipD9tBhN-KuqR59uP5XoLvfBNHHeKToz&index=4&ab_channel=DAVID
    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
        VentanaOpciones abrir = new VentanaOpciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAtrasActionPerformed
//boton guardar
    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        //validar si un campo esta vacio sacado de:
        //https://www.youtube.com/watch?v=jDk3dN3ysp4&ab_channel=C%C3%B3digoXtremo
        //if else para validar que el usuario ingrese los datos necesarios
        if (textoID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresar ID", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (textoCedula.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresar Cedula", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (textoNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresar Nombre", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (textoDireccion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresar Direccion", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (textoCorreo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresar Correo", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (textoFecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor ingresar Fecha", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (textoNacionalidad.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresar Nacionalidad", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (textoEstado.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresar Estado", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (textoObjetivo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresar Objetivo", "Error", JOptionPane.WARNING_MESSAGE);

        } else {
            GuardarDatos();
            JOptionPane.showMessageDialog(null, "Guardado con exito");
        }
    }//GEN-LAST:event_BotonGuardarActionPerformed
//boton siguiente
    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
        VentanaExperienciaLaboral abrir = new VentanaExperienciaLaboral();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonSiguienteActionPerformed

    /*
    Validar que solo se ingresen numero o caracteres sacado de :
    https://www.youtube.com/watch?v=l2n0KAhONwA&ab_channel=BroJav%26Ant
     */
//validar que solo se numeros en ID
    private void textoIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoIDKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_textoIDKeyTyped

//validar que solo se ingresen numeros en Cedula 
    private void textoCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoCedulaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_textoCedulaKeyTyped

//validar que solo se ingresen Caracteres en  nacionalidad
    private void textoNacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNacionalidadKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car)) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_textoNacionalidadKeyTyped

//validar que solo se ingresen caracteres en estado
    private void textoEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoEstadoKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car)) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_textoEstadoKeyTyped
//Boton guardar
    public void GuardarDatos() {
        //atributos
        DatosPersonales datosPersonales = new DatosPersonales();
        DatosPersonalesTXT datosPersonalesTXT = new DatosPersonalesTXT(datosPersonales);
//asignar los datos recolectados por los textField a los atritutos de la clase DatosPersonales
        datosPersonales.setId(textoID.getText());
        datosPersonales.setCedula(textoCedula.getText());
        datosPersonales.setNombre(textoNombre.getText());
        datosPersonales.setDireccion(textoDireccion.getText());
        datosPersonales.setCorreo(textoCorreo.getText());
        datosPersonales.setFechaNacimiento(textoFecha.getDate());
        datosPersonales.setNacionalidad(textoNacionalidad.getText());
        datosPersonales.setEstadoCivil(textoEstado.getText());
        datosPersonales.setObjetivoProfeccional(textoObjetivo.getText());
        
        datosPersonalesTXT.crearArchivo();//llamado de la funcion
        datosPersonalesTXT.AgregarDatos();//llamado de la funcion
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDatosPersonales().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel DatosPersonales;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel FechaNacimiento;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Nacionalidad;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Objetivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField textoCedula;
    private javax.swing.JFormattedTextField textoCorreo;
    private javax.swing.JFormattedTextField textoDireccion;
    private javax.swing.JFormattedTextField textoEstado;
    private com.toedter.calendar.JDateChooser textoFecha;
    private javax.swing.JFormattedTextField textoID;
    private javax.swing.JFormattedTextField textoNacionalidad;
    private javax.swing.JFormattedTextField textoNombre;
    private javax.swing.JFormattedTextField textoObjetivo;
    // End of variables declaration//GEN-END:variables
}
